BellVotingSystem.WEB/Controllers/EntryController.cs
using BellVotingSystem.Data.Models;
using Microsoft.AspNetCore.Mvc;
using BellVotingSystem.Data;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using BellVotingSystem.WEB.Models.Entry;
using System.Linq;
using System;

namespace BellVotingSystem.WEB.Controllers
{
    public class EntryController : Controller
    {
        private readonly VotingSystemDbContext context;

        public EntryController(VotingSystemDbContext context)
        {
            this.context = context;
        }

        public async Task<IActionResult> AllEntries()
        {
            EntriesViewModel model = new EntriesViewModel
            {
                Entry = await context.UsedSongs.OrderByDescending(s => s.ChosenOn).Take(1)
                .Select(s => new EntryViewModel
                {
                    Id = s.Id,
                    Song = s.Song,
                    ChosenOn = s.ChosenOn,
                    IsBlacklisted = false,
                }).FirstOrDefaultAsync(),

                Entries = await context.Entries.OrderByDescending(e => e.VoteCount).Select(e => new EntryViewModel
                {
                    Id = e.Id,
                    Song = e.Song,
                    VoteCount = e.VoteCount,
                    IsBlacklisted = false,
                }).ToListAsync()
            };

            return View(model);
        }

        public async Task<IActionResult> AllBlacklistedSongs()
        {
            EntriesViewModel model = new EntriesViewModel
            {
                Entries = await context.BlacklistedSongs.Select(e => new EntryViewModel()
                {
                    Id = e.Id,
                    Song = e.Song,
                    VoteCount = 0,
                    ChosenOn = new DateTime(),
                    IsBlacklisted = true,
                }).ToListAsync()
            };

            return View("Blacklist", model);
        }

        [HttpGet]
        [ActionName("Add")]
        public IActionResult Add()
        {
            EntryCreateViewModel model = new EntryCreateViewModel();

            return View("AddEntry", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(EntryCreateViewModel model)
        {
            bool hasError = false;

            await foreach (Entry entry in context.Entries)
            {
                if (entry.Song == model.Song)
                {
                    ModelState.AddModelError(nameof(model.Song), "This song is already nominated.");
                    hasError = true;
                    break;
                }
            }

            if (!hasError)
            {
                await foreach (BlacklistedSong blacklistedSong in context.BlacklistedSongs)
                {
                    if (blacklistedSong.Song == model.Song)
                    {
                        ModelState.AddModelError(nameof(model.Song), "This song has been blacklisted. Choose another one.");
                        hasError = true;
                        break;
                    }
                }
            }

            if (!hasError)
            {
                foreach (UsedSong usedSong in context.UsedSongs.OrderByDescending(s => s.ChosenOn).Take(24))
                {
                    if (usedSong.Song == model.Song)
                    {
                        ModelState.AddModelError(nameof(model.Song), "This song has been used in the last 24 weeks. Choose another one.");
                        break;
                    }
                }
            }

            if (ModelState.IsValid)
            {
                Entry entry = new Entry
                {
                    Id = Guid.NewGuid().ToString(),
                    Song = model.Song,
                    VoteCount = 1,
                };

                context.Entries.Add(entry);
                await context.SaveChangesAsync();

                return RedirectToAction(nameof(AllEntries));
            }

            return View("AddEntry", model);
        }

        public async Task<IActionResult> AddToBlacklist(EntriesViewModel model)
        {
            foreach (EntryViewModel entry in model.Entries)
            {
                if (entry.IsBlacklisted)
                {
                    BlacklistedSong bs = new BlacklistedSong
                    {
                        Id = Guid.NewGuid().ToString(),
                        Song = entry.Song,
                    };

                    await context.BlacklistedSongs.AddAsync(bs);

                    Entry e = await context.Entries.FirstOrDefaultAsync(e => e.Id == entry.Id);
                    if (e != null)
                    {
                        context.Entries.Remove(e);
                    }

                    await context.SaveChangesAsync();
                }
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [ActionName("Read")]
        public async Task<IActionResult> Read(string id)
        {
            Entry entry = await context.Entries.SingleOrDefaultAsync(e => e.Id == id);

            EntryViewModel entryViewModel = new EntryViewModel()
            {
                Song = entry.Song,
                VoteCount = entry.VoteCount
            };

            return View("", entryViewModel);
        }

        public async Task<IActionResult> Vote(string id)
        {
            Entry entry = await context.Entries.SingleOrDefaultAsync(e => e.Id == id);
            entry.VoteCount++;
            await context.SaveChangesAsync();
            return RedirectToAction(nameof(AllEntries));
        }
    }
}

BellVotingSystem.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NPMG Bell Voting System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/design.css" />
    <link rel="stylesheet" href="~/css/media.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 ">
            <div class="container">
                <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">
                    <img height="100" src="~/logo.svg" alt="">
                </a>
                <h1>
                    NPMG RING VOTING SYSTEM
                </h1>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                        aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto ">
                        @if (this.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item active">
                                <a class="nav-link text-dark" asp-controller="Entry" asp-action="AllEntries">All Songs</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Entry" asp-action="AllBlacklistedSongs">Blacklist</a>

                            </li>
                        }
                        @if (this.User.IsInRole("MasterAdmin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Users</a>
                            </li>
                        }
                        @if (!this.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link nav-link-white" asp-controller="Home" asp-action="TopFive">Top 5 songs this week</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link nav-link-white" asp-area="Identity" asp-page="/Account/Login">Login</a>
                            </li>

                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Home" asp-action="About">About</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Home" asp-action="Help">Help</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link nav-link-white" asp-area="Identity" asp-page="/Account/Logout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - BellVotingSystem.WEB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>